### ISSUE TITLE
Add PHP 8.1 support

### ISSUE THREAD

**Issue by xnekv03** [eleftrik/laradhoc#10]
Would it be possible to add support for php 8.1?

Thanks

**Comment by eleftrik** [comment]
> Would it be possible to add support for php 8.1?
> 
> Thanks

Hi @xnekv03, yes, it is possible. I only have to find some time to work on it...
Actually, this project is quite "dead", because now I'm using Laravel Sail, which is (one of) the best options to run a Laravel project locally.
But if you're still using Laradhoc, I'll try to add PHP 8.1 support :-)
Or, if you prefer, you can open a Pull Request.

Thanks

**Comment by eleftrik** [comment]
Hi @xnekv03, just released [version 2.3.0](https://github.com/eleftrik/laradhoc/releases/tag/2.3.0) with PHP `8.1` support.
Let me know if it's working for you

👋🏻

**Comment by xnekv03** [comment]
works, thank you
