### ISSUE TITLE
Can't access localhost

### ISSUE THREAD

**Issue by 77media-creations** [eleftrik/laradhoc#2]
Hi, I tried the exact steps to setup Laradhoc.<br>
Everything seems to be up and running in dokcker. I can access composer and artisan commands in terminal but unable to access localhost.<br><br>

I was able to execute `artisan serve` command successfully but upon visiting `http://127.0.0.1:8000` returns "This site can't be reached".
<br><br>

I use Mac and have correct entries in my etc/hosts file.
<br><br>

Please inform if I'm missing anything as it is my first time using docker.

**Comment by eleftrik** [comment]
Hi @77media-creations, you don't need to run `php artisan serve`, because your site should be accessible via http(s)://`$APP_HOST`, depending on your `.env` variables.

For example, assuming you're using default values (as per `.env.example` file), after adding an entry in your `/etc/hosts` file (`127.0.0.1 laradhoc.test`), after running `.docker/scripts/init` (only once) and `.docker/scripts/starts`, your site should be accessible at `https://laradhoc.test`(if you don't need HTTPS, you can set `NGINX_ENABLE_HTTPS=0` and the address will be `http://laradhoc.test`).

Please let me know if you're encountering still errors or something didn't work.
In this case, please share your `.env` file (omitting sensitive information).
The output of `docker ps` could also be useful.

**Comment by 77media-creations** [comment]
I removed it and installed/created the containers again and somehow it is working now.
Thanks
