### ISSUE TITLE
server requirment are too much complaix can you help me through the process in a easy way please i want to use larvel as my backend support with react

### ISSUE THREAD

**Issue by madilraza** [eleftrik/laradhoc#4]
PHP >= 7.2.5
BCMath PHP Extension
Ctype PHP Extension
Fileinfo PHP extension
JSON PHP Extension
Mbstring PHP Extension
OpenSSL PHP Extension
PDO PHP Extension
Tokenizer PHP Extension
XML PHP Extension

**Comment by eleftrik** [comment]
@madilraza Sorry, but I can't understand exactly what you need.

Every software, framework or similar have requirements. They're not complex; in a Linux environment, for example, you could install all these extensions through `apt ` (or similar). You can find plenty of tutorials.

Anyway, the purpose of **Laradhoc** is **exactly** this: providing an already configured stack via Docker, with PHP and all the needed extensions, so that you don't have to worry about installing manually the needed software.

Just follow https://github.com/eleftrik/laradhoc/blob/master/README.md step by step instructions and you'll have a fresh version of Laravel running on your development workstation.
